### ISSUE TITLE
Issue running generation/sampling code

### ISSUE THREAD

**Issue by moqingyan** [mugen-org/MUGEN_baseline#5]
Hi,

I am trying to run the sampling shell script MUGEN_baseline/generation/experiments/gpt/V2T/eval/sampling/L16.sh and ran into a few issues. 

1. directory setup: The data directory seems to be hard coded in the checkpoint file. By printing the arguments setting up the vqvae, I obtained the following output with "checkpoint/songyangzhang/videogpt/":
```
> python generation/sample_gpt.py --input_modality video --output_modality text --gpt_ckpt_file checkpoints/generation/V2T/VideoTextGPT_L16/epoch=54-step=599999.ckpt --sequence_length 16 --sample_every_n_frames 6 --output_dir /checkpoint/VideoTextGPT_L16 --get_game_frame --use_manual_annotation --top_k 1 --top_p 0.5

Namespace(logger=True, checkpoint_callback=True, default_root_dir='/checkpoint/songyangzhang/mugen/VideoTextGPT_L16', gradient_clip_val=0.0, gradient_clip_algorithm='norm', process_position=0, num_nodes=1, num_processes=1, gpus=8, auto_select_gpus=False, tpu_cores=None, log_gpu_memory=None, progress_bar_refresh_rate=100, overfit_batches=0.0, track_grad_norm=-1, check_val_every_n_epoch=1, fast_dev_run=False, accumulate_grad_batches=1, max_epochs=None, min_epochs=None, max_steps=600000, min_steps=None, max_time=None, limit_train_batches=1.0, limit_val_batches=1.0, limit_test_batches=1.0, limit_predict_batches=1.0, val_check_interval=1.0, flush_logs_every_n_steps=100, log_every_n_steps=50, accelerator=None, sync_batchnorm=True, precision=32, weights_summary='top', weights_save_path=None, num_sanity_val_steps=2, truncated_bptt_steps=None, resume_from_checkpoint=None, profiler=None, benchmark=False, deterministic=False, reload_dataloaders_every_epoch=False, auto_lr_find=False, replace_sampler_ddp=True, terminate_on_nan=False, auto_scale_batch_size=False, prepare_data_per_node=True, plugins=None, amp_backend='native', amp_level='O2', distributed_backend=None, move_metrics_to_cpu=False, multiple_trainloader_mode='max_size_cycle', stochastic_weight_avg=False, input_modality='video', output_modality='text', hidden_dim=768, heads=8, layers=12, dropout=0.2, attn_dropout=0.3, loss_video_weight=7.0, loss_audio_weight=1, loss_text_weight=1, lr=0.0003, video_vqvae='/checkpoint/songyangzhang/videogpt/vqvae_default_1node_l16s6k3_full/lightning_logs/version_53229223/checkpoints/epoch=54-step=599999.ckpt', audio_vqvae=None, tokenizer_file='/checkpoint/songyangzhang/datasets/coinrun/tokenizers/tokenizer-coinrun_1024.json', text_seq_len=128, sample_every_n_frames=6, sequence_length=16, resolution=256, audio_sample_rate=22050, audio_sample_length=70560.0, bbox_smap_for_agent=False, bbox_smap_for_monsters=False, use_manual_annotation=True, use_auto_annotation=False, use_downsampled_trainset=False, fixed_start_idx=False, no_fixed_padding=False, get_game_frame=True, get_seg_map=False, get_text_desc=True, get_audio=False, debug=False, data_path='/checkpoint/songyangzhang/datasets/coinrun/coinrun_dataset_jsons/release', batch_size=4, num_workers=32, pretrained_model=None)
```
2. After I manually overwrite the arguments to the correct paths, I obtained the following runtime error, saying the setup for the vqvae model has missing arguments.
```
Traceback (most recent call last):
  File "<MY_HOME_DIR>/Project/MUGEN_baseline/generation/sample_gpt.py", line 74, in <module>
    save_samples(args)
  File "<MY_HOME_DIR>/Project/MUGEN_baseline/generation/sample_gpt.py", line 36, in save_samples
    gpt_model = MMGPT.load_from_checkpoint(args.gpt_ckpt_file).cuda()
  File "<MY_HOME_DIR>//miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/<MY_HOME_DIR>//miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 199, in _load_model_state
    model = cls(**_cls_kwargs)
  File "<MY_HOME_DIR>/Project/MUGEN_baseline/generation/../lib/models/gpt/gpt.py", line 25, in __init__
    self.setup_video_vqvae()
  File "<MY_HOME_DIR>/Project/MUGEN_baseline/generation/../lib/models/gpt/gpt.py", line 84, in setup_video_vqvae
    self.video_vqvae = VQVAE.load_from_checkpoint(self.args.video_vqvae)
  File "<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 199, in _load_model_state
    model = cls(**_cls_kwargs)
  File "<MY_HOME_DIR>/Project/MUGEN_baseline/generation/../lib/models/video_vqvae/vqvae.py", line 36, in __init__
    self.encoder = Encoder(args.n_hiddens, args.n_res_layers, args.downsample, self.image_channels, kernel_size)
AttributeError: 'Namespace' object has no attribute 'n_res_layers'
```
3. So I tried both the argument setup in default value and training shell script, but all of them gives state_dict mismatch error:
```
 File "<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state
    model.load_state_dict(checkpoint['state_dict'], strict=strict)
  File "<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VQVAE:
        Missing key(s) in state_dict: "encoder.convs.0.conv.weight", "encoder.convs.0.conv.bias", "encoder.convs.1.conv.weight", "encoder.convs.1.conv.bias", "encoder.conv_last.conv.weight", "encoder.conv_last.conv.bias", "encoder.res_stack.0.block.0.weight", "encoder.res_stack.0.block.0.bias", "encoder.res_stack.0.block.0.running_mean", "encoder.res_stack.0.block.0.running_var", "encoder.res_stack.0.block.2.conv.weight", "encoder.res_stack.0.block.3.weight", "encoder.res_stack.0.block.3.bias", "encoder.res_stack.0.block.3.running_mean", "encoder.res_stack.0.block.3.running_var", "encoder.res_stack.0.block.5.conv.weight", "encoder.res_stack.0.block.6.weight", "encoder.res_stack.0.block.6.bias", "encoder.res_stack.0.block.6.running_mean", "encoder.res_stack.0.block.6.running_var", "encoder.res_stack.0.block.8.attn_w.w_qs.weight", "encoder.res_stack.0.block.8.attn_w.w_ks.weight", "encoder.res_stack.0.block.8.attn_w.w_vs.weight", "encoder.res_stack.0.block.8.attn_w.fc.weight", "encoder.res_stack.0.block.8.attn_w.fc.bias", "encoder.res_stack.0.block.8.attn_h.w_qs.weight", "encoder.res_stack.0.block.8.attn_h.w_ks.weight", "encoder.res_stack.0.block.8.attn_h.w_vs.weight", "encoder.res_stack.0.block.8.attn_h.fc.weight",
```

Can you help me with loading the '.ckpt' module? I believe I have other issues loading the other modules as well. :)

**Comment by Sy-Zhang** [comment]
> Hi,
> 
> I am trying to run the sampling shell script MUGEN_baseline/generation/experiments/gpt/V2T/eval/sampling/L16.sh and ran into a few issues.
> 
> 1. directory setup: The data directory seems to be hard coded in the checkpoint file. By printing the arguments setting up the vqvae, I obtained the following output with "checkpoint/songyangzhang/videogpt/":
> 
> ```
> > python generation/sample_gpt.py --input_modality video --output_modality text --gpt_ckpt_file checkpoints/generation/V2T/VideoTextGPT_L16/epoch=54-step=599999.ckpt --sequence_length 16 --sample_every_n_frames 6 --output_dir /checkpoint/VideoTextGPT_L16 --get_game_frame --use_manual_annotation --top_k 1 --top_p 0.5
> 
> Namespace(logger=True, checkpoint_callback=True, default_root_dir='/checkpoint/songyangzhang/mugen/VideoTextGPT_L16', gradient_clip_val=0.0, gradient_clip_algorithm='norm', process_position=0, num_nodes=1, num_processes=1, gpus=8, auto_select_gpus=False, tpu_cores=None, log_gpu_memory=None, progress_bar_refresh_rate=100, overfit_batches=0.0, track_grad_norm=-1, check_val_every_n_epoch=1, fast_dev_run=False, accumulate_grad_batches=1, max_epochs=None, min_epochs=None, max_steps=600000, min_steps=None, max_time=None, limit_train_batches=1.0, limit_val_batches=1.0, limit_test_batches=1.0, limit_predict_batches=1.0, val_check_interval=1.0, flush_logs_every_n_steps=100, log_every_n_steps=50, accelerator=None, sync_batchnorm=True, precision=32, weights_summary='top', weights_save_path=None, num_sanity_val_steps=2, truncated_bptt_steps=None, resume_from_checkpoint=None, profiler=None, benchmark=False, deterministic=False, reload_dataloaders_every_epoch=False, auto_lr_find=False, replace_sampler_ddp=True, terminate_on_nan=False, auto_scale_batch_size=False, prepare_data_per_node=True, plugins=None, amp_backend='native', amp_level='O2', distributed_backend=None, move_metrics_to_cpu=False, multiple_trainloader_mode='max_size_cycle', stochastic_weight_avg=False, input_modality='video', output_modality='text', hidden_dim=768, heads=8, layers=12, dropout=0.2, attn_dropout=0.3, loss_video_weight=7.0, loss_audio_weight=1, loss_text_weight=1, lr=0.0003, video_vqvae='/checkpoint/songyangzhang/videogpt/vqvae_default_1node_l16s6k3_full/lightning_logs/version_53229223/checkpoints/epoch=54-step=599999.ckpt', audio_vqvae=None, tokenizer_file='/checkpoint/songyangzhang/datasets/coinrun/tokenizers/tokenizer-coinrun_1024.json', text_seq_len=128, sample_every_n_frames=6, sequence_length=16, resolution=256, audio_sample_rate=22050, audio_sample_length=70560.0, bbox_smap_for_agent=False, bbox_smap_for_monsters=False, use_manual_annotation=True, use_auto_annotation=False, use_downsampled_trainset=False, fixed_start_idx=False, no_fixed_padding=False, get_game_frame=True, get_seg_map=False, get_text_desc=True, get_audio=False, debug=False, data_path='/checkpoint/songyangzhang/datasets/coinrun/coinrun_dataset_jsons/release', batch_size=4, num_workers=32, pretrained_model=None)
> ```
> 
> 2. After I manually overwrite the arguments to the correct paths, I obtained the following runtime error, saying the setup for the vqvae model has missing arguments.
> 
> ```
> Traceback (most recent call last):
>   File "<MY_HOME_DIR>/Project/MUGEN_baseline/generation/sample_gpt.py", line 74, in <module>
>     save_samples(args)
>   File "<MY_HOME_DIR>/Project/MUGEN_baseline/generation/sample_gpt.py", line 36, in save_samples
>     gpt_model = MMGPT.load_from_checkpoint(args.gpt_ckpt_file).cuda()
>   File "<MY_HOME_DIR>//miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
>     model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
>   File "/<MY_HOME_DIR>//miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 199, in _load_model_state
>     model = cls(**_cls_kwargs)
>   File "<MY_HOME_DIR>/Project/MUGEN_baseline/generation/../lib/models/gpt/gpt.py", line 25, in __init__
>     self.setup_video_vqvae()
>   File "<MY_HOME_DIR>/Project/MUGEN_baseline/generation/../lib/models/gpt/gpt.py", line 84, in setup_video_vqvae
>     self.video_vqvae = VQVAE.load_from_checkpoint(self.args.video_vqvae)
>   File "<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
>     model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
>   File "<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 199, in _load_model_state
>     model = cls(**_cls_kwargs)
>   File "<MY_HOME_DIR>/Project/MUGEN_baseline/generation/../lib/models/video_vqvae/vqvae.py", line 36, in __init__
>     self.encoder = Encoder(args.n_hiddens, args.n_res_layers, args.downsample, self.image_channels, kernel_size)
> AttributeError: 'Namespace' object has no attribute 'n_res_layers'
> ```
> 
> 3. So I tried both the argument setup in default value and training shell script, but all of them gives state_dict mismatch error:
> 
> ```
>  File "<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state
>     model.load_state_dict(checkpoint['state_dict'], strict=strict)
>   File "<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for VQVAE:
>         Missing key(s) in state_dict: "encoder.convs.0.conv.weight", "encoder.convs.0.conv.bias", "encoder.convs.1.conv.weight", "encoder.convs.1.conv.bias", "encoder.conv_last.conv.weight", "encoder.conv_last.conv.bias", "encoder.res_stack.0.block.0.weight", "encoder.res_stack.0.block.0.bias", "encoder.res_stack.0.block.0.running_mean", "encoder.res_stack.0.block.0.running_var", "encoder.res_stack.0.block.2.conv.weight", "encoder.res_stack.0.block.3.weight", "encoder.res_stack.0.block.3.bias", "encoder.res_stack.0.block.3.running_mean", "encoder.res_stack.0.block.3.running_var", "encoder.res_stack.0.block.5.conv.weight", "encoder.res_stack.0.block.6.weight", "encoder.res_stack.0.block.6.bias", "encoder.res_stack.0.block.6.running_mean", "encoder.res_stack.0.block.6.running_var", "encoder.res_stack.0.block.8.attn_w.w_qs.weight", "encoder.res_stack.0.block.8.attn_w.w_ks.weight", "encoder.res_stack.0.block.8.attn_w.w_vs.weight", "encoder.res_stack.0.block.8.attn_w.fc.weight", "encoder.res_stack.0.block.8.attn_w.fc.bias", "encoder.res_stack.0.block.8.attn_h.w_qs.weight", "encoder.res_stack.0.block.8.attn_h.w_ks.weight", "encoder.res_stack.0.block.8.attn_h.w_vs.weight", "encoder.res_stack.0.block.8.attn_h.fc.weight",
> ```
> 
> Can you help me with loading the '.ckpt' module? I believe I have other issues loading the other modules as well. :)

Hi, I have fixed this problem on my local machine. Please check my latest commit.

**Comment by moqingyan** [comment]
Hey, thank you for the fix! I am going through the models. In V2T, L8, L16 model can be loaded successfully, while L32 model still have issues loading the model.
```
 python generation/sample_gpt.py --input_modality video --output_modality text --gpt_ckpt_file checkpoints/generation/V2T/VideoTextGPT_L32/epoch=54-step=599999.ckpt --video_vqvae checkpoints/generation/video_vqvae/L16/epoch=54-step=599999.ckpt --sequence_length 32 --sample_every_n_frames 3 --output_dir checkpoints/generation/V2T/VideoTextGPT_L32 --get_game_frame --use_manual_annotation --top_k 1 --top_p 0.5

Traceback (most recent call last):
  File ""<MY_HOME_DIR>/Project/original-mugen/MUGEN_baseline/generation/sample_gpt.py", line 72, in <module>
    save_samples(args)
  File ""<MY_HOME_DIR>/Project/original-mugen/MUGEN_baseline/generation/sample_gpt.py", line 34, in save_samples
    gpt_model = MMGPT.load_from_checkpoint(args.gpt_ckpt_file, args=args).cuda()
  File ""<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File ""<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state
    model.load_state_dict(checkpoint['state_dict'], strict=strict)
  File "<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MMGPT:
        size mismatch for attn_stack.video_pos_emb.emb.d_0: copying a param with shape torch.Size([8, 256]) from checkpoint, the shape in current model is torch.Size([4, 256]).
        size mismatch for attn_stack.attn_nets.0.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
        size mismatch for attn_stack.attn_nets.1.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
        size mismatch for attn_stack.attn_nets.2.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
        size mismatch for attn_stack.attn_nets.3.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
        size mismatch for attn_stack.attn_nets.4.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
        size mismatch for attn_stack.attn_nets.5.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
        size mismatch for attn_stack.attn_nets.6.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
        size mismatch for attn_stack.attn_nets.7.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
        size mismatch for attn_stack.attn_nets.8.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
        size mismatch for attn_stack.attn_nets.9.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
        size mismatch for attn_stack.attn_nets.10.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
        size mismatch for attn_stack.attn_nets.11.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
```

**Comment by Sy-Zhang** [comment]
> Hey, thank you for the fix! I am going through the models. In V2T, L8, L16 model can be loaded successfully, while L32 model still have issues loading the model.
> 
> ```
>  python generation/sample_gpt.py --input_modality video --output_modality text --gpt_ckpt_file checkpoints/generation/V2T/VideoTextGPT_L32/epoch=54-step=599999.ckpt --video_vqvae checkpoints/generation/video_vqvae/L16/epoch=54-step=599999.ckpt --sequence_length 32 --sample_every_n_frames 3 --output_dir checkpoints/generation/V2T/VideoTextGPT_L32 --get_game_frame --use_manual_annotation --top_k 1 --top_p 0.5
> 
> Traceback (most recent call last):
>   File ""<MY_HOME_DIR>/Project/original-mugen/MUGEN_baseline/generation/sample_gpt.py", line 72, in <module>
>     save_samples(args)
>   File ""<MY_HOME_DIR>/Project/original-mugen/MUGEN_baseline/generation/sample_gpt.py", line 34, in save_samples
>     gpt_model = MMGPT.load_from_checkpoint(args.gpt_ckpt_file, args=args).cuda()
>   File ""<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
>     model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
>   File ""<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state
>     model.load_state_dict(checkpoint['state_dict'], strict=strict)
>   File "<MY_HOME_DIR>/miniconda/envs/mugen/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for MMGPT:
>         size mismatch for attn_stack.video_pos_emb.emb.d_0: copying a param with shape torch.Size([8, 256]) from checkpoint, the shape in current model is torch.Size([4, 256]).
>         size mismatch for attn_stack.attn_nets.0.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
>         size mismatch for attn_stack.attn_nets.1.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
>         size mismatch for attn_stack.attn_nets.2.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
>         size mismatch for attn_stack.attn_nets.3.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
>         size mismatch for attn_stack.attn_nets.4.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
>         size mismatch for attn_stack.attn_nets.5.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
>         size mismatch for attn_stack.attn_nets.6.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
>         size mismatch for attn_stack.attn_nets.7.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
>         size mismatch for attn_stack.attn_nets.8.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
>         size mismatch for attn_stack.attn_nets.9.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
>         size mismatch for attn_stack.attn_nets.10.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
>         size mismatch for attn_stack.attn_nets.11.attn.attn.mask: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([384, 384]).
> ```

Thanks for pointing this out. Just fixed it.
